<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="translationsCategoriesLanguages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="scope" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="I" type="xs:string" minOccurs="0"/>
                            <xs:element name="M" type="xs:string" minOccurs="0"/>
                            <xs:element name="S" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="type" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="A" type="xs:string" minOccurs="0"/>
                            <xs:element name="C" type="xs:string" minOccurs="0"/>
                            <xs:element name="E" type="xs:string" minOccurs="0"/>
                            <xs:element name="H" type="xs:string" minOccurs="0"/>
                            <xs:element name="L" type="xs:string" minOccurs="0"/>
                            <xs:element name="S" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="language" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>