<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Root element -->
    <xs:element name="translationsCategoriesLanguages">
        <xs:complexType>
            <xs:sequence>

                <!-- scope -->
                <xs:element name="scope">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="I" type="xs:string"/>
                            <xs:element name="M" type="xs:string"/>
                            <xs:element name="S" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- type -->
                <xs:element name="type">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="A" type="xs:string"/>
                            <xs:element name="C" type="xs:string"/>
                            <xs:element name="E" type="xs:string"/>
                            <xs:element name="H" type="xs:string"/>
                            <xs:element name="L" type="xs:string"/>
                            <xs:element name="S" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <!-- Attribute -->
            <xs:attribute name="language" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>