<?php

/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

return [
    'Adlm' => [
        'name' => 'Adlam'
    ],
    'Afak' => [
        'name' => 'Afaka'
    ],
    'Aghb' => [
        'name' => 'Caucasian Albanian'
    ],
    'Ahom' => [
        'name' => 'Ahom, Tai Ahom'
    ],
    'Arab' => [
        'name' => 'Arabic'
    ],
    'Aran' => [
        'name' => 'Arabic (Nastaliq variant)'
    ],
    'Armi' => [
        'name' => 'Imperial Aramaic'
    ],
    'Armn' => [
        'name' => 'Armenian'
    ],
    'Avst' => [
        'name' => 'Avestan'
    ],
    'Bali' => [
        'name' => 'Balinese'
    ],
    'Bamu' => [
        'name' => 'Bamum'
    ],
    'Bass' => [
        'name' => 'Bassa Vah'
    ],
    'Batk' => [
        'name' => 'Batak'
    ],
    'Beng' => [
        'name' => 'Bengali (Bangla)'
    ],
    'Berf' => [
        'name' => 'Beria Erfe'
    ],
    'Bhks' => [
        'name' => 'Bhaiksuki'
    ],
    'Blis' => [
        'name' => 'Blissymbols'
    ],
    'Bopo' => [
        'name' => 'Bopomofo'
    ],
    'Brah' => [
        'name' => 'Brahmi'
    ],
    'Brai' => [
        'name' => 'Braille'
    ],
    'Bugi' => [
        'name' => 'Buginese'
    ],
    'Buhd' => [
        'name' => 'Buhid'
    ],
    'Cakm' => [
        'name' => 'Chakma'
    ],
    'Cans' => [
        'name' => 'Unified Canadian Aboriginal Syllabics'
    ],
    'Cari' => [
        'name' => 'Carian'
    ],
    'Cham' => [
        'name' => 'Cham'
    ],
    'Cher' => [
        'name' => 'Cherokee'
    ],
    'Chis' => [
        'name' => 'Chisoi'
    ],
    'Chrs' => [
        'name' => 'Chorasmian'
    ],
    'Cirt' => [
        'name' => 'Cirth'
    ],
    'Copt' => [
        'name' => 'Coptic'
    ],
    'Cpmn' => [
        'name' => 'Cypro-Minoan'
    ],
    'Cprt' => [
        'name' => 'Cypriot syllabary'
    ],
    'Cyrl' => [
        'name' => 'Cyrillic'
    ],
    'Cyrs' => [
        'name' => 'Cyrillic (Old Church Slavonic variant)'
    ],
    'Deva' => [
        'name' => 'Devanagari (Nagari)'
    ],
    'Diak' => [
        'name' => 'Dives Akuru'
    ],
    'Dogr' => [
        'name' => 'Dogra'
    ],
    'Dsrt' => [
        'name' => 'Deseret (Mormon)'
    ],
    'Dupl' => [
        'name' => 'Duployan shorthand, Duployan stenography'
    ],
    'Egyd' => [
        'name' => 'Egyptian demotic'
    ],
    'Egyh' => [
        'name' => 'Egyptian hieratic'
    ],
    'Egyp' => [
        'name' => 'Egyptian hieroglyphs'
    ],
    'Elba' => [
        'name' => 'Elbasan'
    ],
    'Elym' => [
        'name' => 'Elymaic'
    ],
    'Ethi' => [
        'name' => 'Ethiopic (Geʻez)'
    ],
    'Gara' => [
        'name' => 'Garay'
    ],
    'Geok' => [
        'name' => 'Khutsuri (Asomtavruli and Nuskhuri)'
    ],
    'Geor' => [
        'name' => 'Georgian (Mkhedruli and Mtavruli)'
    ],
    'Glag' => [
        'name' => 'Glagolitic'
    ],
    'Gong' => [
        'name' => 'Gunjala Gondi'
    ],
    'Gonm' => [
        'name' => 'Masaram Gondi'
    ],
    'Goth' => [
        'name' => 'Gothic'
    ],
    'Gran' => [
        'name' => 'Grantha'
    ],
    'Grek' => [
        'name' => 'Greek'
    ],
    'Gujr' => [
        'name' => 'Gujarati'
    ],
    'Gukh' => [
        'name' => 'Gurung Khema'
    ],
    'Guru' => [
        'name' => 'Gurmukhi'
    ],
    'Hanb' => [
        'name' => 'Han with Bopomofo (alias for Han + Bopomofo)'
    ],
    'Hang' => [
        'name' => 'Hangul (Hangŭl, Hangeul)'
    ],
    'Hani' => [
        'name' => 'Han (Hanzi, Kanji, Hanja)'
    ],
    'Hano' => [
        'name' => 'Hanunoo (Hanunóo)'
    ],
    'Hans' => [
        'name' => 'Han (Simplified variant)'
    ],
    'Hant' => [
        'name' => 'Han (Traditional variant)'
    ],
    'Hatr' => [
        'name' => 'Hatran'
    ],
    'Hebr' => [
        'name' => 'Hebrew'
    ],
    'Hira' => [
        'name' => 'Hiragana'
    ],
    'Hluw' => [
        'name' => 'Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)'
    ],
    'Hmng' => [
        'name' => 'Pahawh Hmong'
    ],
    'Hmnp' => [
        'name' => 'Nyiakeng Puachue Hmong'
    ],
    'Hntl' => [
        'name' => 'Han (Traditional variant) with Latin (alias for Hant + Latn)'
    ],
    'Hrkt' => [
        'name' => 'Japanese syllabaries (alias for Hiragana + Katakana)'
    ],
    'Hung' => [
        'name' => 'Old Hungarian (Hungarian Runic)'
    ],
    'Inds' => [
        'name' => 'Indus (Harappan)'
    ],
    'Ital' => [
        'name' => 'Old Italic (Etruscan, Oscan, etc.)'
    ],
    'Jamo' => [
        'name' => 'Jamo (alias for Jamo subset of Hangul)'
    ],
    'Java' => [
        'name' => 'Javanese'
    ],
    'Jpan' => [
        'name' => 'Japanese (alias for Han + Hiragana + Katakana)'
    ],
    'Jurc' => [
        'name' => 'Jurchen'
    ],
    'Kali' => [
        'name' => 'Kayah Li'
    ],
    'Kana' => [
        'name' => 'Katakana'
    ],
    'Kawi' => [
        'name' => 'Kawi'
    ],
    'Khar' => [
        'name' => 'Kharoshthi'
    ],
    'Khmr' => [
        'name' => 'Khmer'
    ],
    'Khoj' => [
        'name' => 'Khojki'
    ],
    'Kitl' => [
        'name' => 'Khitan large script'
    ],
    'Kits' => [
        'name' => 'Khitan small script'
    ],
    'Knda' => [
        'name' => 'Kannada'
    ],
    'Kore' => [
        'name' => 'Korean (alias for Hangul + Han)'
    ],
    'Kpel' => [
        'name' => 'Kpelle'
    ],
    'Krai' => [
        'name' => 'Kirat Rai'
    ],
    'Kthi' => [
        'name' => 'Kaithi'
    ],
    'Lana' => [
        'name' => 'Tai Tham (Lanna)'
    ],
    'Laoo' => [
        'name' => 'Lao'
    ],
    'Latf' => [
        'name' => 'Latin (Fraktur variant)'
    ],
    'Latg' => [
        'name' => 'Latin (Gaelic variant)'
    ],
    'Latn' => [
        'name' => 'Latin'
    ],
    'Leke' => [
        'name' => 'Leke'
    ],
    'Lepc' => [
        'name' => 'Lepcha (Róng)'
    ],
    'Limb' => [
        'name' => 'Limbu'
    ],
    'Lina' => [
        'name' => 'Linear A'
    ],
    'Linb' => [
        'name' => 'Linear B'
    ],
    'Lisu' => [
        'name' => 'Lisu (Fraser)'
    ],
    'Loma' => [
        'name' => 'Loma'
    ],
    'Lyci' => [
        'name' => 'Lycian'
    ],
    'Lydi' => [
        'name' => 'Lydian'
    ],
    'Mahj' => [
        'name' => 'Mahajani'
    ],
    'Maka' => [
        'name' => 'Makasar'
    ],
    'Mand' => [
        'name' => 'Mandaic, Mandaean'
    ],
    'Mani' => [
        'name' => 'Manichaean'
    ],
    'Marc' => [
        'name' => 'Marchen'
    ],
    'Maya' => [
        'name' => 'Mayan hieroglyphs'
    ],
    'Medf' => [
        'name' => 'Medefaidrin (Oberi Okaime, Oberi Ɔkaimɛ)'
    ],
    'Mend' => [
        'name' => 'Mende Kikakui'
    ],
    'Merc' => [
        'name' => 'Meroitic Cursive'
    ],
    'Mero' => [
        'name' => 'Meroitic Hieroglyphs'
    ],
    'Mlym' => [
        'name' => 'Malayalam'
    ],
    'Modi' => [
        'name' => 'Modi, Moḍī'
    ],
    'Mong' => [
        'name' => 'Mongolian'
    ],
    'Moon' => [
        'name' => 'Moon (Moon code, Moon script, Moon type)'
    ],
    'Mroo' => [
        'name' => 'Mro, Mru'
    ],
    'Mtei' => [
        'name' => 'Meitei Mayek (Meithei, Meetei)'
    ],
    'Mult' => [
        'name' => 'Multani'
    ],
    'Mymr' => [
        'name' => 'Myanmar (Burmese)'
    ],
    'Nagm' => [
        'name' => 'Nag Mundari'
    ],
    'Nand' => [
        'name' => 'Nandinagari'
    ],
    'Narb' => [
        'name' => 'Old North Arabian (Ancient North Arabian)'
    ],
    'Nbat' => [
        'name' => 'Nabataean'
    ],
    'Newa' => [
        'name' => 'Newa, Newar, Newari, Nepāla lipi'
    ],
    'Nkdb' => [
        'name' => 'Naxi Dongba (Nakhi Tomba)'
    ],
    'Nkgb' => [
        'name' => 'Naxi Geba (Nakhi Geba)'
    ],
    'Nkoo' => [
        'name' => 'N’Ko'
    ],
    'Nshu' => [
        'name' => 'Nüshu'
    ],
    'Ogam' => [
        'name' => 'Ogham'
    ],
    'Olck' => [
        'name' => 'Ol Chiki (Ol Cemet’, Ol, Santali)'
    ],
    'Onao' => [
        'name' => 'Ol Onal'
    ],
    'Orkh' => [
        'name' => 'Old Turkic, Orkhon Runic'
    ],
    'Orya' => [
        'name' => 'Oriya (Odia)'
    ],
    'Osge' => [
        'name' => 'Osage'
    ],
    'Osma' => [
        'name' => 'Osmanya'
    ],
    'Ougr' => [
        'name' => 'Old Uyghur'
    ],
    'Palm' => [
        'name' => 'Palmyrene'
    ],
    'Pauc' => [
        'name' => 'Pau Cin Hau'
    ],
    'Pcun' => [
        'name' => 'Proto-Cuneiform'
    ],
    'Pelm' => [
        'name' => 'Proto-Elamite'
    ],
    'Perm' => [
        'name' => 'Old Permic'
    ],
    'Phag' => [
        'name' => 'Phags-pa'
    ],
    'Phli' => [
        'name' => 'Inscriptional Pahlavi'
    ],
    'Phlp' => [
        'name' => 'Psalter Pahlavi'
    ],
    'Phlv' => [
        'name' => 'Book Pahlavi'
    ],
    'Phnx' => [
        'name' => 'Phoenician'
    ],
    'Piqd' => [
        'name' => 'Klingon (KLI pIqaD)'
    ],
    'Plrd' => [
        'name' => 'Miao (Pollard)'
    ],
    'Prti' => [
        'name' => 'Inscriptional Parthian'
    ],
    'Psin' => [
        'name' => 'Proto-Sinaitic'
    ],
    'Qaaa' => [
        'name' => 'Reserved for private use (start)'
    ],
    'Qabx' => [
        'name' => 'Reserved for private use (end)'
    ],
    'Ranj' => [
        'name' => 'Ranjana'
    ],
    'Rjng' => [
        'name' => 'Rejang (Redjang, Kaganga)'
    ],
    'Rohg' => [
        'name' => 'Hanifi Rohingya'
    ],
    'Roro' => [
        'name' => 'Rongorongo'
    ],
    'Runr' => [
        'name' => 'Runic'
    ],
    'Samr' => [
        'name' => 'Samaritan'
    ],
    'Sara' => [
        'name' => 'Sarati'
    ],
    'Sarb' => [
        'name' => 'Old South Arabian'
    ],
    'Saur' => [
        'name' => 'Saurashtra'
    ],
    'Seal' => [
        'name' => '(Small) Seal'
    ],
    'Sgnw' => [
        'name' => 'SignWriting'
    ],
    'Shaw' => [
        'name' => 'Shavian (Shaw)'
    ],
    'Shrd' => [
        'name' => 'Sharada, Śāradā'
    ],
    'Shui' => [
        'name' => 'Shuishu'
    ],
    'Sidd' => [
        'name' => 'Siddham, Siddhaṃ, Siddhamātṛkā'
    ],
    'Sidt' => [
        'name' => 'Sidetic'
    ],
    'Sind' => [
        'name' => 'Khudawadi, Sindhi'
    ],
    'Sinh' => [
        'name' => 'Sinhala'
    ],
    'Sogd' => [
        'name' => 'Sogdian'
    ],
    'Sogo' => [
        'name' => 'Old Sogdian'
    ],
    'Sora' => [
        'name' => 'Sora Sompeng'
    ],
    'Soyo' => [
        'name' => 'Soyombo'
    ],
    'Sund' => [
        'name' => 'Sundanese'
    ],
    'Sunu' => [
        'name' => 'Sunuwar'
    ],
    'Sylo' => [
        'name' => 'Syloti Nagri'
    ],
    'Syrc' => [
        'name' => 'Syriac'
    ],
    'Syre' => [
        'name' => 'Syriac (Estrangelo variant)'
    ],
    'Syrj' => [
        'name' => 'Syriac (Western variant)'
    ],
    'Syrn' => [
        'name' => 'Syriac (Eastern variant)'
    ],
    'Tagb' => [
        'name' => 'Tagbanwa'
    ],
    'Takr' => [
        'name' => 'Takri, Ṭākrī, Ṭāṅkrī'
    ],
    'Tale' => [
        'name' => 'Tai Le'
    ],
    'Talu' => [
        'name' => 'New Tai Lue'
    ],
    'Taml' => [
        'name' => 'Tamil'
    ],
    'Tang' => [
        'name' => 'Tangut'
    ],
    'Tavt' => [
        'name' => 'Tai Viet'
    ],
    'Tayo' => [
        'name' => 'Tai Yo'
    ],
    'Telu' => [
        'name' => 'Telugu'
    ],
    'Teng' => [
        'name' => 'Tengwar'
    ],
    'Tfng' => [
        'name' => 'Tifinagh (Berber)'
    ],
    'Tglg' => [
        'name' => 'Tagalog (Baybayin, Alibata)'
    ],
    'Thaa' => [
        'name' => 'Thaana'
    ],
    'Thai' => [
        'name' => 'Thai'
    ],
    'Tibt' => [
        'name' => 'Tibetan'
    ],
    'Tirh' => [
        'name' => 'Tirhuta'
    ],
    'Tnsa' => [
        'name' => 'Tangsa'
    ],
    'Todr' => [
        'name' => 'Todhri'
    ],
    'Tols' => [
        'name' => 'Tolong Siki'
    ],
    'Toto' => [
        'name' => 'Toto'
    ],
    'Tutg' => [
        'name' => 'Tulu-Tigalari'
    ],
    'Ugar' => [
        'name' => 'Ugaritic'
    ],
    'Vaii' => [
        'name' => 'Vai'
    ],
    'Visp' => [
        'name' => 'Visible Speech'
    ],
    'Vith' => [
        'name' => 'Vithkuqi'
    ],
    'Wara' => [
        'name' => 'Warang Citi (Varang Kshiti)'
    ],
    'Wcho' => [
        'name' => 'Wancho'
    ],
    'Wole' => [
        'name' => 'Woleai'
    ],
    'Xpeo' => [
        'name' => 'Old Persian'
    ],
    'Xsux' => [
        'name' => 'Cuneiform, Sumero-Akkadian'
    ],
    'Yezi' => [
        'name' => 'Yezidi'
    ],
    'Yiii' => [
        'name' => 'Yi'
    ],
    'Zanb' => [
        'name' => 'Zanabazar Square (Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script)'
    ],
    'Zinh' => [
        'name' => 'Code for inherited script'
    ],
    'Zmth' => [
        'name' => 'Mathematical notation'
    ],
    'Zsye' => [
        'name' => 'Symbols (Emoji variant)'
    ],
    'Zsym' => [
        'name' => 'Symbols'
    ],
    'Zxxx' => [
        'name' => 'Code for unwritten documents'
    ],
    'Zyyy' => [
        'name' => 'Code for undetermined script'
    ],
    'Zzzz' => [
        'name' => 'Code for uncoded script'
    ]
];
