<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="languages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="language" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="isoCode" type="xs:string" minOccurs="0"/>
                            <xs:element name="part2b" type="xs:string" minOccurs="0" nillable="true"/>
                            <xs:element name="part2t" type="xs:string" minOccurs="0" nillable="true"/>
                            <xs:element name="part1" type="xs:string" minOccurs="0" nillable="true"/>
                            <xs:element name="glottoCode" type="xs:string" minOccurs="0" nillable="true"/>
                            <xs:element name="scope">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="code" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="type">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="code" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="macroLanguageRef" type="xs:string" minOccurs="0" nillable="true"/>
                            <xs:element name="scripts">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="script" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="index" type="xs:int" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
