<?php

/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

return [
    'Adlm' => [
        'name' => 'Adlam'
    ],
    'Afak' => [
        'name' => 'Afaka'
    ],
    'Aghb' => [
        'name' => 'Albanese caucasico'
    ],
    'Ahom' => [
        'name' => 'Ahom, Tai Ahom'
    ],
    'Arab' => [
        'name' => 'Arabo'
    ],
    'Aran' => [
        'name' => 'Arabo (nasta\'liq)'
    ],
    'Armi' => [
        'name' => 'Aramaico biblico'
    ],
    'Armn' => [
        'name' => 'Armeno'
    ],
    'Avst' => [
        'name' => 'Avestico'
    ],
    'Bali' => [
        'name' => 'Balinese'
    ],
    'Bamu' => [
        'name' => 'Bamum'
    ],
    'Bass' => [
        'name' => 'Bassa Vah'
    ],
    'Batk' => [
        'name' => 'Batak'
    ],
    'Beng' => [
        'name' => 'Bengalese (Bangla)'
    ],
    'Berf' => [
        'name' => 'Beria Erfe'
    ],
    'Bhks' => [
        'name' => 'Bhaiksuki'
    ],
    'Blis' => [
        'name' => 'Blissymbol'
    ],
    'Bopo' => [
        'name' => 'Bopomofo'
    ],
    'Brah' => [
        'name' => 'Brahmi'
    ],
    'Brai' => [
        'name' => 'Braille'
    ],
    'Bugi' => [
        'name' => 'Buginese'
    ],
    'Buhd' => [
        'name' => 'Buhid'
    ],
    'Cakm' => [
        'name' => 'Chakma'
    ],
    'Cans' => [
        'name' => 'Sillabario Aborigeno Canadese Unificato'
    ],
    'Cari' => [
        'name' => 'Carian'
    ],
    'Cham' => [
        'name' => 'Cham'
    ],
    'Cher' => [
        'name' => 'Cherokee'
    ],
    'Chis' => [
        'name' => 'Chisoi'
    ],
    'Chrs' => [
        'name' => 'Corasmiano'
    ],
    'Cirt' => [
        'name' => 'Cirth'
    ],
    'Copt' => [
        'name' => 'Copto'
    ],
    'Cpmn' => [
        'name' => 'Cipro-Minoico'
    ],
    'Cprt' => [
        'name' => 'Cipriota'
    ],
    'Cyrl' => [
        'name' => 'Cirillico'
    ],
    'Cyrs' => [
        'name' => 'Cirillico (slavo ecclesiastico antico)'
    ],
    'Deva' => [
        'name' => 'Devanagari (Nagari)'
    ],
    'Diak' => [
        'name' => 'Akuru dives'
    ],
    'Dogr' => [
        'name' => 'Dogra'
    ],
    'Dsrt' => [
        'name' => 'Deseret'
    ],
    'Dupl' => [
        'name' => 'Stenografia duployan'
    ],
    'Egyd' => [
        'name' => 'Egizio demotico'
    ],
    'Egyh' => [
        'name' => 'Egizio ieratico'
    ],
    'Egyp' => [
        'name' => 'Egizio geroglifico'
    ],
    'Elba' => [
        'name' => 'Elbasan'
    ],
    'Elym' => [
        'name' => 'Elimaico'
    ],
    'Ethi' => [
        'name' => 'Etiope (Geʻez)'
    ],
    'Gara' => [
        'name' => 'Garay'
    ],
    'Geok' => [
        'name' => 'Khutsuri (Asomtavruli e Nuskhuri)'
    ],
    'Geor' => [
        'name' => 'Georgiano (Mkhedruli e Mtavruli)'
    ],
    'Glag' => [
        'name' => 'Glagolitico'
    ],
    'Gong' => [
        'name' => 'Gunjala gondi'
    ],
    'Gonm' => [
        'name' => 'Masaram gondi'
    ],
    'Goth' => [
        'name' => 'Gotico'
    ],
    'Gran' => [
        'name' => 'Grantha'
    ],
    'Grek' => [
        'name' => 'Greco'
    ],
    'Gujr' => [
        'name' => 'Gugiarati (Gujarati)'
    ],
    'Gukh' => [
        'name' => 'Gurung Khema'
    ],
    'Guru' => [
        'name' => 'Gurmukhi'
    ],
    'Hanb' => [
        'name' => 'Han con Bopomofo (alias per Han + Bopomofo)'
    ],
    'Hang' => [
        'name' => 'Hangul (Hang\' l, Hangeul)'
    ],
    'Hani' => [
        'name' => 'Han (Hanzi, Kanji, Hanja)'
    ],
    'Hano' => [
        'name' => 'Hanunoo (Hanunóo)'
    ],
    'Hans' => [
        'name' => 'Han (variante semplificata)'
    ],
    'Hant' => [
        'name' => 'Han (variante tradizionale)'
    ],
    'Hatr' => [
        'name' => 'Hatrena (Aramaico di Hatra)'
    ],
    'Hebr' => [
        'name' => 'Ebraico'
    ],
    'Hira' => [
        'name' => 'Hiragana'
    ],
    'Hluw' => [
        'name' => 'Geroglifici anatolici (Geroglifici luvi, Geroglifici ittiti)'
    ],
    'Hmng' => [
        'name' => 'Pahawh Hmong'
    ],
    'Hmnp' => [
        'name' => 'Nyiakeng Puachue Hmong'
    ],
    'Hntl' => [
        'name' => 'Han (variante tradizionale) con latino (alias per Hant + Latn)'
    ],
    'Hrkt' => [
        'name' => 'Sillabari giapponesi (alias per Hiragana + Katakana)'
    ],
    'Hung' => [
        'name' => 'Ungherese antico (runico ungherese)'
    ],
    'Inds' => [
        'name' => 'Indo (Harappa)'
    ],
    'Ital' => [
        'name' => 'Italico antico (etrusco, osco, ecc...)'
    ],
    'Jamo' => [
        'name' => 'Jamo (alias per il sottoinsieme Jamo di Hangul)'
    ],
    'Java' => [
        'name' => 'Giavanese'
    ],
    'Jpan' => [
        'name' => 'Giapponese (alias per Han + Hiragana + Katakana)'
    ],
    'Jurc' => [
        'name' => 'Jurchen'
    ],
    'Kali' => [
        'name' => 'Kayah Li'
    ],
    'Kana' => [
        'name' => 'Katakana'
    ],
    'Kawi' => [
        'name' => 'Kawi'
    ],
    'Khar' => [
        'name' => 'Kharoshthi'
    ],
    'Khmr' => [
        'name' => 'Cambogiano (Khmer)'
    ],
    'Khoj' => [
        'name' => 'Khojki'
    ],
    'Kitl' => [
        'name' => 'Alfabeto Kitai grande'
    ],
    'Kits' => [
        'name' => 'Alfabeto Kitai piccolo'
    ],
    'Knda' => [
        'name' => 'Canarese (Kannada, Cànara, Kànara)'
    ],
    'Kore' => [
        'name' => 'Coreano (alias per Hangul + Han)'
    ],
    'Kpel' => [
        'name' => 'Kpelle'
    ],
    'Krai' => [
        'name' => 'Kirat Rai'
    ],
    'Kthi' => [
        'name' => 'Kaithi'
    ],
    'Lana' => [
        'name' => 'Tai Tham (Lanna)'
    ],
    'Laoo' => [
        'name' => 'Laotiano, Laosiano, Laoziano'
    ],
    'Latf' => [
        'name' => 'Latino (scrittura Fraktur)'
    ],
    'Latg' => [
        'name' => 'Latino (scrittura gaelica)'
    ],
    'Latn' => [
        'name' => 'Latino'
    ],
    'Leke' => [
        'name' => 'Leke'
    ],
    'Lepc' => [
        'name' => 'Lepcha (Róng)'
    ],
    'Limb' => [
        'name' => 'Limbu'
    ],
    'Lina' => [
        'name' => 'Lineare A'
    ],
    'Linb' => [
        'name' => 'Lineare B'
    ],
    'Lisu' => [
        'name' => 'Lisu (Fraser)'
    ],
    'Loma' => [
        'name' => 'Loma'
    ],
    'Lyci' => [
        'name' => 'Licio'
    ],
    'Lydi' => [
        'name' => 'Lidio'
    ],
    'Mahj' => [
        'name' => 'Mahajani'
    ],
    'Maka' => [
        'name' => 'Makasar'
    ],
    'Mand' => [
        'name' => 'Mandaico, Mandei'
    ],
    'Mani' => [
        'name' => 'Manicheo'
    ],
    'Marc' => [
        'name' => 'Marchen'
    ],
    'Maya' => [
        'name' => 'Geroglifici Maya'
    ],
    'Medf' => [
        'name' => 'Medefaidrin (Oberi Okaime)'
    ],
    'Mend' => [
        'name' => 'Mende Kikakui'
    ],
    'Merc' => [
        'name' => 'Corsivo meroitico'
    ],
    'Mero' => [
        'name' => 'Geroglifici meroitici'
    ],
    'Mlym' => [
        'name' => 'Malayalam'
    ],
    'Modi' => [
        'name' => 'Modi'
    ],
    'Mong' => [
        'name' => 'Mongolo'
    ],
    'Moon' => [
        'name' => 'Moon (codice Moon, scrittura Moon, tipo Moon)'
    ],
    'Mroo' => [
        'name' => 'Mro, Mru'
    ],
    'Mtei' => [
        'name' => 'Meitei Mayek (Meithei, Meetei)'
    ],
    'Mult' => [
        'name' => 'Multani'
    ],
    'Mymr' => [
        'name' => 'Birmano (Myanmar)'
    ],
    'Nagm' => [
        'name' => 'Nag Mundari'
    ],
    'Nand' => [
        'name' => 'Nandinagari'
    ],
    'Narb' => [
        'name' => 'Arabo Settentrionale Antico'
    ],
    'Nbat' => [
        'name' => 'Nabateo'
    ],
    'Newa' => [
        'name' => 'Newa, Newari, Newar, Nevar, Lipi nepalese'
    ],
    'Nkdb' => [
        'name' => 'Naxi Dongba (Nakhi Tomba)'
    ],
    'Nkgb' => [
        'name' => 'Naxi Geba (Nakhi Geba)'
    ],
    'Nkoo' => [
        'name' => 'N’Ko'
    ],
    'Nshu' => [
        'name' => 'Nü shu'
    ],
    'Ogam' => [
        'name' => 'Ogham'
    ],
    'Olck' => [
        'name' => 'Ol Chiki (Ol Chemet’, Ol, Santali)'
    ],
    'Onao' => [
        'name' => 'Ol Onal'
    ],
    'Orkh' => [
        'name' => 'Turco antico, Orkhon runico'
    ],
    'Orya' => [
        'name' => 'Odia (Oriya)'
    ],
    'Osge' => [
        'name' => 'Osage'
    ],
    'Osma' => [
        'name' => 'Osmanya, Somalo'
    ],
    'Ougr' => [
        'name' => 'Uiguro antico'
    ],
    'Palm' => [
        'name' => 'Palmireno'
    ],
    'Pauc' => [
        'name' => 'Pau Cin Hau'
    ],
    'Pcun' => [
        'name' => 'Protocuneiforme'
    ],
    'Pelm' => [
        'name' => 'Protoelamico'
    ],
    'Perm' => [
        'name' => 'Permico antico (Permiano antico)'
    ],
    'Phag' => [
        'name' => '\'Phags-pa'
    ],
    'Phli' => [
        'name' => 'Pahlavi, Pahlevi (iscrizioni)'
    ],
    'Phlp' => [
        'name' => 'Pahlavi, Pahlevi (salterio)'
    ],
    'Phlv' => [
        'name' => 'Pahlavi, Pahlevi (libro)'
    ],
    'Phnx' => [
        'name' => 'Fenicio'
    ],
    'Piqd' => [
        'name' => 'Klingon (pIqaD)'
    ],
    'Plrd' => [
        'name' => 'Pollard (Miao Pollard)'
    ],
    'Prti' => [
        'name' => 'Parto (iscrizioni)'
    ],
    'Psin' => [
        'name' => 'Proto-Sinaitico'
    ],
    'Qaaa' => [
        'name' => 'Riservato per uso privato (start)'
    ],
    'Qabx' => [
        'name' => 'Riservato per uso privato (end)'
    ],
    'Ranj' => [
        'name' => 'Ranjana'
    ],
    'Rjng' => [
        'name' => 'Rejang (Redjang, Kaganga)'
    ],
    'Rohg' => [
        'name' => 'Rohingya hanifi'
    ],
    'Roro' => [
        'name' => 'Rongorongo'
    ],
    'Runr' => [
        'name' => 'Runico'
    ],
    'Samr' => [
        'name' => 'Samaritano'
    ],
    'Sara' => [
        'name' => 'Sarati'
    ],
    'Sarb' => [
        'name' => 'Arabo meridionale antico'
    ],
    'Saur' => [
        'name' => 'Saurashtra'
    ],
    'Seal' => [
        'name' => 'Sigillario'
    ],
    'Sgnw' => [
        'name' => 'Sutton SignWriting, SignWriting, Scrittura dei segni'
    ],
    'Shaw' => [
        'name' => 'Shaviano'
    ],
    'Shrd' => [
        'name' => 'Sharada, Śāradā, Charada'
    ],
    'Shui' => [
        'name' => 'Shuishu, Sui'
    ],
    'Sidd' => [
        'name' => 'Siddham, Siddhaṃ, Siddhamātṛkā'
    ],
    'Sidt' => [
        'name' => 'Sidetico'
    ],
    'Sind' => [
        'name' => 'Khudawadi, Sindhi'
    ],
    'Sinh' => [
        'name' => 'Singalese, Cingalese, Ceylonese, Silonense, Sinhala'
    ],
    'Sogd' => [
        'name' => 'Sogdian'
    ],
    'Sogo' => [
        'name' => 'Sogdiano antico'
    ],
    'Sora' => [
        'name' => 'Sora Sompeng'
    ],
    'Soyo' => [
        'name' => 'Soyombo'
    ],
    'Sund' => [
        'name' => 'Sundanese, Sondanese'
    ],
    'Sunu' => [
        'name' => 'Sunuwar'
    ],
    'Sylo' => [
        'name' => 'Sylheti, Sileṭ Nagri'
    ],
    'Syrc' => [
        'name' => 'Siriaco'
    ],
    'Syre' => [
        'name' => 'Siriaco (variante ʾEsṭrangēlā)'
    ],
    'Syrj' => [
        'name' => 'Siriaco (variante occidentale)'
    ],
    'Syrn' => [
        'name' => 'Siriaco (variante orientale)'
    ],
    'Tagb' => [
        'name' => 'Tagbanwa, Aborlan Tagbanwa, Apurawnon'
    ],
    'Takr' => [
        'name' => 'Takri'
    ],
    'Tale' => [
        'name' => 'Tai Le'
    ],
    'Talu' => [
        'name' => 'Nuovo Tai lue, Tai lue semplificato'
    ],
    'Taml' => [
        'name' => 'Tàmil, Tàmul'
    ],
    'Tang' => [
        'name' => 'Tangut'
    ],
    'Tavt' => [
        'name' => 'Tai Viet'
    ],
    'Tayo' => [
        'name' => 'Tai Yo'
    ],
    'Telu' => [
        'name' => 'Tèlugu'
    ],
    'Teng' => [
        'name' => 'Tengwar'
    ],
    'Tfng' => [
        'name' => 'Tifinagh (Berbero)'
    ],
    'Tglg' => [
        'name' => 'Tagalog, Tagalo'
    ],
    'Thaa' => [
        'name' => 'Thaana, Taana, Tāna'
    ],
    'Thai' => [
        'name' => 'Tailandese'
    ],
    'Tibt' => [
        'name' => 'Tibetano'
    ],
    'Tirh' => [
        'name' => 'Tirhuta'
    ],
    'Tnsa' => [
        'name' => 'Tangsa'
    ],
    'Todr' => [
        'name' => 'Todhri'
    ],
    'Tols' => [
        'name' => 'Tolong Siki'
    ],
    'Toto' => [
        'name' => 'Toto'
    ],
    'Tutg' => [
        'name' => 'Tigalari, Tulu'
    ],
    'Ugar' => [
        'name' => 'Ugaritico'
    ],
    'Vaii' => [
        'name' => 'Vai'
    ],
    'Visp' => [
        'name' => 'Discorso visibile'
    ],
    'Vith' => [
        'name' => 'Vithkuqi, Büthakukye, Beitha Kukju'
    ],
    'Wara' => [
        'name' => 'Warang Chiti (Varang Kshiti)'
    ],
    'Wcho' => [
        'name' => 'Wancho'
    ],
    'Wole' => [
        'name' => 'Woleai'
    ],
    'Xpeo' => [
        'name' => 'Persiano antico'
    ],
    'Xsux' => [
        'name' => 'Cuneiforme, Sumero-Accadico'
    ],
    'Yezi' => [
        'name' => 'Yezidi'
    ],
    'Yiii' => [
        'name' => 'Yi'
    ],
    'Zanb' => [
        'name' => 'Zanabazar quadrato (Scrittura Orizontale Quadrata)'
    ],
    'Zinh' => [
        'name' => 'Codice per script ereditato'
    ],
    'Zmth' => [
        'name' => 'Notazione matematica'
    ],
    'Zsye' => [
        'name' => 'Simboli (variante Emoji)'
    ],
    'Zsym' => [
        'name' => 'Simboli'
    ],
    'Zxxx' => [
        'name' => 'Codice per documenti non scritti'
    ],
    'Zyyy' => [
        'name' => 'Codice per script indeterminato'
    ],
    'Zzzz' => [
        'name' => 'Codice per script non codificato'
    ]
];
